mock:
  services:
    - name: calculator1
      mockPort: 10088
      targetHost: localhost
      targetPort: 8088
      fieldsToClear: timeStamp,nonExistingField
      endpointType: HTTP
    - name: calculator2
      mockPort: 10089
      targetHost: localhost
      targetPort: 8089
      mockBeanName: simpleCalculatorMock
    - name: sampleTcpClientServer
      mockPort: 10090
      targetHost: localhost
      targetPort: 30814
    - name: amazon
      mockPort: 10091
      targetHost: localhost
      targetPort: 9090
      fieldsToClear: BrowseNodeId
      endpointType: HTTP